apiVersion: v1
kind: Pod
metadata: 
  name: apache
  namespace: application
spec: 
  containers:
    - name: apache
      image: paketobuildpacks/httpd:0.7

      # Error: failed to generate container "d2a966524ab1f4ac9bd58b7d2dcc96ebf51755155776a9ba988d6035a47f1768" spec: failed to generate spec: no command specified


      # command: ["httpd-foreground"]
      # Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: 
      # unable to start container process: exec: "httpd-foreground": executable file not found in $PATH: unknown


      # env: 
      #   - name: BP_WEB_SERVER
      #     value: "httpd"
    # Error: failed to generate container "6d0cb6355d4963680fe08525357d2061797fcfaa0965d0919448aacbd8e9bf8b" spec: failed to generate spec: no command specified


      ports: 
        - containerPort: 80